CHANEGLOG.md
src/index.ts
src/lib/getConfig.ts
src/lib/runNewmanWith.ts
src/lib/transforms/disableOptionalParams.ts

- use resolve path instead of relative
- we were providing the default to test-suite incorrectly

properly resolve paths and allow collections without tests

---

CHANEGLOG.md
src/application/TestSuite.ts

Temporary fix for handling multiple content-types, where the contract will be based on t he 1st content-type that is defined in the OpenAPI response.
There are a number of ways to solve this, so we are looking into an option that is easy to configure with the test injection.

Temporary fix for multiple content-types

---

src/application/globals/injectEnvVariables.ts

Fix for #99, which solves "spreadArray is not a function" since the __spreadArrays function for TypeScript has been deprecated

Bugfix - spreadArray is not a function

---

src/application/globals/writeCollectionPreRequestScripts.ts
src/application/overwrites/overwriteRequestPathIdVariables.ts
src/application/preRequests/writeOperationPreRequestScripts.ts

The error "spreadArray is not a function" occurs because the __spreadArrays function for TypeScript has been deprecated.
This PR aims to replace the "spreadArray" usage with a compatible implementation.
Linked to #99

Replace "spreadArray" with compatible implementation

---

src/application/TestSuite.ts
src/types/PortmanConfig.ts

This PR fixes a problem where contract tests' `enabled` flag was ignored during tests generation.

fix: contract tests enabled flag

---

CHANGELOG.md
src/Portman.ts
src/services/PostmanApiService.ts
src/services/PostmanSyncService.ts

This PR handles the collection name
```
var results = this.cache.collections.filter(function (collection) { return collection.name.toLowerCase() === name.toLowerCase(); });
^
TypeError: Cannot read properties of undefined (reading ‘toLowerCase’)
```

Fix missing Collection name

---

README.md
examples/testsuite-contract-tests/readme.md
src/application/TestSuite.ts
src/application/tests/__snapshots__/testResponseJsonSchema.test.ts.snap
src/application/tests/testResponseJsonSchema.test.ts
src/application/tests/testResponseJsonSchema.ts
src/types/PortmanConfig.ts
src/utils/portman-config-schema.json

Contract test - extend JSON schema validation with option to set additional properties behaviour.
Linked to  #192

Contract test - JSON Schema - additional properties

---

README.md
src/application/globals/__fixtures__/samplePreRequest1.js
src/application/globals/__fixtures__/samplePreRequest2.js
src/application/globals/__snapshots__/writeCollectionPreRequestScripts.test.ts.snap
src/application/globals/writeCollectionPreRequestScripts.test.ts
src/application/globals/writeCollectionPreRequestScripts.ts
src/application/preRequests/__fixtures__/samplePreRequest1.js
src/application/preRequests/__fixtures__/samplePreRequest2.js
src/application/preRequests/__snapshots__/writeOperationPreRequestScripts.test.ts.snap
src/application/preRequests/writeOperationPreRequestScripts.test.ts
src/application/preRequests/writeOperationPreRequestScripts.ts

Allow `collectionPreRequestScripts` and `operationPreRequestScripts` to import local script files by specifying `file:` followed by the file path, e.g. `file:scripts/auth-pre-request.js`.
**Use Case:** Our API collections have quite complex pre-request scripts. In order to manage them, currently we keep those scripts in separate files, and we have to copy their contents into portman config file manually when we make any change. 
It is quite tedious and error-prone process so I think it would be great if portman can support importing the script files out of the box.
Please let me know if this feature can be incorporated and if there is any change required for the PR.
Thanks very much for creating and maintaining this tool.
Cheers,

Add support for importing files for operationPreRequestScripts and collectionPreRequestScripts

---

examples/testsuite-fuzzing-tests/readme.md

I fixed two minor issues in the fuzzy readme file.

fix fuzzing doc issues for request query params

---

src/application/tests/testResponseJsonSchema.ts

When float as format is used the actual tests will fail. This is addition they shouldn't.

Valid schema when float as a format is used

---

src/application/globals/writeRawReplacements.test.ts
src/application/globals/writeRawReplacements.ts

When using Portman, we wanted to use replacements to modify the generated JSON schema tests. However, we couldn't get it to work as described in the documentation.
To test our use cases, I added two tests which either replace parts of the JSON schema with an empty string (to delete parts) or another string (to modify parts). I then corrected the used pattern in the writeRawReplacements function to make the tests pass.

Adapt replacements to modify json schema tests

---

CHANGELOG.md
src/application/newman/runNewmanWith.ts

The Newman CLI expects options as param-cased, while when using Newman as a NodeJS module the options are camelCase

Fix passing Newman options during Newman execution

---

CHANGELOG.md
README.md
examples/postman-ordering/readme.md
package.json

Updated ordering example docs

---

package-lock.json
package.json
src/application/overwrites/__snapshots__/overwriteRequestBaseUrl.test.ts.snap
src/application/overwrites/overwriteRequestBaseUrl.test.ts
src/application/overwrites/overwriteRequestBaseUrl.ts

When the `overwriteRequestBaseUrl` has a path parameter it is not included in the overwrite. For example,
`{{newUrl}}/subPath` will result in a host of `{{newUrl}}` while `subPath` will be discarded. This change will include `subPath` at the start of the `path` array in the postman spec

fix: overwriteRequestBaseUrl - overwrite value with path parameters excludes parameters

---

src/application/IntegrationTestWriter.ts

Generates multiple file names for the same integration test folder, because it's using the folder id from the operation.

Fix folder name

---

src/application/globals/overwriteCollectionSecurityValues.test.ts
src/application/globals/overwriteCollectionSecurityValues.ts

securityOverwrites - Set auth when no auth is defined

---

CHANGELOG.md
src/application/overwrites/__snapshots__/overwriteRequestSecurity.test.ts.snap
src/application/overwrites/overwriteRequestSecurity.test.ts
src/application/overwrites/overwriteRequestSecurity.ts

overwriteRequestSecurity - Keep API key when no key

---

src/services/PostmanApiService.ts

The following change resolves the `ERR_FR_MAX_BODY_LENGTH_EXCEEDED` error, which happens if the source file is 3.6 MB. 
Command: 
portman -u https://fake.swagger.cloud/documentation/json  --collectionName "Test" --syncPostman --postmanFastSync

fix(collection): set no limit to the body size on collection update

---

src/application/tests/__snapshots__/testResponseBodyContent.test.ts.snap
src/application/tests/testResponseBodyContent.test.ts
src/application/tests/testResponseBodyContent.ts

Add pm variable support for `oneOf` assertions in content tests

feat: oneOf pm variables

---

src/application/Fuzzer.test.ts
src/application/Fuzzer.ts
src/application/__snapshots__/Fuzzer.test.ts.snap

Instructs the fuzzer to treat properties with reserved names as properties instead of meta keywords that guide test generation. For example, a property called 'required' should be seen as a property and not the list of required properties on an object.

Fix #513: Exclude properties with reserved names.

---

src/services/DownloadService.ts

In the current version of Portman if the API spec URL includes extra parameters/query strings, then the generated file name includes those parameters and Portman can't use the file in that format. I suggest to change it so that extra query parameters can be removed, when processing the URL and generating file from it.

removes extra parameters from url when processing

---

src/application/overwrites/__snapshots__/overwriteRequestBody.test.ts.snap
src/application/overwrites/overwriteRequestBody.test.ts
src/application/overwrites/overwriteRequestBody.ts

`overwriteRequestBody` isn't taking the `overwrite` flag into account when overwriting the root (`.`). It's my understanding from the docs that the request body should only be merged when `overwrite` is `false`.
Fixes https://github.com/apideck-libraries/portman/issues/480

fix: overwriteRequestBody root should overwrite

---

README.md
examples/testsuite-assign-overwrite/readme.md
examples/testsuite-assign-variables/readme.md

It looks like an earlier version of the docs used the standard Swagger pets API spec for example. 
The latest docs now reference operations from the CRM spec, but in a few places still refer back to /pets endpoints.

remove references to /pets

---

README.md
examples/testsuite-assign-overwrite/readme.md
examples/testsuite-assign-variables/readme.md
examples/testsuite-contract-tests/default-portman-config.json
examples/testsuite-contract-tests/portman-config.crm.yml
examples/testsuite-contract-tests/readme.md

As a new Portman user I struggled a bit getting up to speed.  There is SO much info in the readme.   After the getting started, the initial readme jumps into things like portman CLI configuration and Postman/Newman variables, but as a new user I was more interested in learning about what types of tests the tool could make and how to set them up.   It actually took me several days of playing with it, reading the main readme from top to bottom, and accidentally discovering that I was getting contract tests despite being misconfigured, before I began to realize how to process the documentation.
TL:DR - the "good stuff" is really in the examples!
With that in mind here are some suggested changes that might make it easier for other first time users.   I won't be upset if you don't choose to …

Update getting started -- feedback welcome

---

src/utils/PortmanError.ts

* changed the exit code to a non zero value

Portman error exit code

---

CHANGELOG.md
src/utils/parseTpl.test.ts
src/utils/parseTpl.ts

linked to #597 
```yaml
overwrites:
- openApiOperation: "PATCH::/crm/leads/{id}"
overwriteRequestBody:
- key: monetary_amount
value: '{{{<tag>MonetaryAmount}}}'
overwrite: true
```
Result in: 
BEFORE
AFTER

Template expression: Fix to handle double/triple curly braces

---

CHANGELOG.md
README.md
__tests__/fixtures/crm-run.yml
__tests__/fixtures/postman-config.run.json
postman-config.default.json
postman-config.example.json
postman-config.k6.json
src/Portman.test.ts
src/__snapshots__/Portman.test.ts.snap
src/services/OpenApiToPostmanService.ts

Linked to #601 
After the implementation of the ConvertV2, the result will be that the first-listed content-type from a request body will be taken when there are multiple request bodies instead of the default URL_ENCODED or FORM_DATA.

Conversion - Use convertV2 from openapi-to-postman

---

package-lock.json
package.json
src/__snapshots__/Portman.test.ts.snap

Linked to #628 
Readonly & write-only properties are now converted with V2 of openapi-to-postman.
OpenAPI:
Before:
After:

Skip read-only properties from request body

---

CHANGELOG.md
README.md
src/application/CollectionWriter.ts
src/application/globals/index.ts
src/application/globals/orderCollectionFolders.test.ts
src/application/globals/orderCollectionFolders.ts
src/types/PortmanConfig.ts
src/utils/portman-config-schema.json

linked to #621 
- **orderOfFolders** : The `orderOfFolders` is a list of Postman folder names, which is used by Portman to sort the Postman folders in the desired order. Folders that are **not** defined in the `orderOfFolders` list will remain at their current order, after the re-order folders.
```
globals:
orderOfFolders:
- Regulations
- Vehicle Systems
- Vehicle Types
```
BEFORE:
AFTER:

Sort Postman folders based on the "orderOfFolders" configuration

---

src/application/overwrites/overwriteRequestQueryParams.test.ts
src/application/overwrites/overwriteRequestQueryParams.ts

linked to #640 
OpenAPI
```
parameters:
...
- name: ids
in: query
description: >
A form serialized array of category IDs to filter the results. <br>
IDs that do not exist are ignored.
required: false
schema:
type: array
items:
type: integer
style: form
examples:
child_ids:
value:
- 315162
- 315163
- 315164
top_level:
value:
- 83
- 84
```
Portman Config
```
"overwrites": [
{
"openApiOperation": "*::*",
"overwriteRequestQueryParams": [
{
"key": "name",
"value": "{{newName}}"
},
{
"key": "ids",
"value": "{{_categoryId1}}"
},
{
"key": "first",
"value": "{{newFirst}}"
},
{
"key": "ids",
"value": "{{_categoryId2}}"
},
{
"key": "ids",
"value": "{{_categoryId3}}"
}
,
{
"key": "number",
"value": "{{newNumber1}}"
},
{
"key": "number",
"value": "{{newNumber2}}"
},
{
"key": "word",
"value": …
```

overwriteRequestQueryParams - Handle form encoded array query params

---

src/utils/setByPath.test.ts
src/utils/setByPath.ts

linked to #646 
Result before:
```
/Path/to/repro/node_modules/dot-object/index.js:118
throw new Error("Trying to redefine non-empty obj['" + k + "']")
^
Error: Trying to redefine non-empty obj['startDateTime']
at DotObject._fill (/Path/to/repro/node_modules/dot-object/index.js:118:15)
at DotObject._fill (/Path/to/repro/node_modules/dot-object/index.js:114:10)
at DotObject.str (/Path/to/repro/node_modules/dot-object/index.js:179:10)
```
Result after:

overwrite - handle overwrite of non-empty objects with plain values

---

README.md
examples/testsuite-content-tests/readme.md

Document the ability to set key to "." in order to apply a responseBodyTest against the entire response for APIs that return single values like a number or a boolean

Doc value as dot for entire result

---

CHANGELOG.md
src/utils/matchPath.test.ts
src/utils/matchPath.ts

matchPath - Improved matching with ending wildcard

---

src/application/Fuzzer.test.ts
src/application/Fuzzer.ts

Added a type check (Array.isArray(node.required)) in the Fuzzer logic to ensure only arrays are processed as required fields.
This change prevents runtime errors and ensures the Fuzzer works correctly with OpenAPI schemas that have properties named required, which are not intended to be arrays of required fields.

fix(fuzzer): only map required fields if node.required is an array
