- src/application/OpenApiToPostmanService.ts
- src/index.ts
Implemented openapi-to-postman as a Service instead of using execShellCommand
> PR openapi-to-postman as package

- CHANEGLOG.md
- package-lock.json
- package.json
- src/index.ts
- src/lib/execShellCommand.ts
- src/lib/index.ts
- src/types/PortmanOptions.ts
- enable pre-conversion filtering of spec
> adds openapi-format dep to filter operations

- __tests__/fixtures/portman.crm.json
- examples/testsuite-assign-variables/portman.crm.json
- examples/testsuite-assign-variables/readme.md
- examples/testsuite-content-tests/readme.md
- examples/testsuite-overwrites/readme.md
- examples/testsuite-response-tests/readme.md
- src/application/TestSuite.ts
- src/types/portmanConfig.ts
Refactored `assignPmVariables` to `assignVariables`
> 1.0.0 alpha assign variables

- src/application/tests/testResponseJsonSchema.ts
Added fix for unwanted minItems in the JSON schema validation
> 1.0.0 alpha minItem fix

- package.json
- portman-config.default.json
- postman-config.default.json
- src/Portman.ts
- src/index.ts
- src/types/PortmanOptions.ts
Added default portman-config & postman-config to facilitate getting started
> 1.0.0 - Default portman & postman configs

- __tests__/fixtures/portman-variations.crm.json
- examples/testsuite-variation-tests/crm.postman.json
- examples/testsuite-variation-tests/portman-config.crm.json
- examples/testsuite-variation-tests/readme.md
- portman-config.example.json
- src/application/TestSuite.test.ts
- src/application/TestSuite.ts
- src/types/portmanConfig.ts
Added "variationTests" targeting for openApiResponse code
> variation target with openApiResponse code

- CHANEGLOG.md
- README.md
- package-lock.json
- package.json
- src/Portman.ts
- src/index.ts
- src/types/PortmanOptions.ts
Added the option to load a existing postman collection and skip the openAPI to postman conversion
> localPostman CLI option

- src/services/DownloadService.ts
Fix to handle remote sources ending with a trailing /
> #82 - support trailing / for url parameter

- CHANEGLOG.md
- package-lock.json
- package.json
- src/services/DownloadService.ts
> #63 - Enhancement - Phased out "node-fetch" in favour of "Axios"

- CHANEGLOG.md
- src/Portman.ts
- src/index.ts
- src/services/DownloadService.ts
- src/utils/promptInit.ts
ci/cd flows need to be able to determine when an error has occurred vs Portman just being finished...
> stop using exit(0) on fails

- CHANEGLOG.md
- README.md
- src/Portman.ts
- src/services/PostmanService.ts
Solves the #88 plus improved the upload postman output for consistency and clarity
> #88 - Fix to handle invalid postmanUid

- package-lock.json
- package.json
- src/types/PortmanConfig.ts
- src/utils/portman-config-schema.json
Added additional types to the json schema validation + added  "ts-json-schema-generator" as a dev dependency
> Added additional types to the json schema validation

- README.md
> Docs: Fixup readme update

- src/Portman.ts
- src/services/PostmanApiService.ts
- src/services/index.ts
Minor - enhanced the Postman API upload error message
> Enhance Postman API error message display

- CHANGELOG.md
- src/application/tests/__snapshots__/testResponseJsonSchema.test.ts.snap
- src/application/tests/testResponseJsonSchema.test.ts
- src/application/tests/testResponseJsonSchema.ts
Bug fix for unwanted maxItems on the root level of a JSON Schema validation
> Bug fix max items

- CHANGELOG.md
- README.md
- package.json
- src/application/variables/__snapshots__/assignVarFromResponseBody.test.ts.snap
- src/application/variables/assignVarFromResponseBody.test.ts
- src/application/variables/assignVarFromResponseBody.ts
> Handle array for assign responseBodyProp

- CHANGELOG.md
- README.md
- examples/cli-options/newman-options.json
- examples/cli-options/portman-cli-options-newman.json
- examples/cli-options/portman-config.crm.yaml
- examples/cli-options/readme.md
- src/index.ts
- src/types/PortmanOptions.ts
Added `newmanOptionsFile` as a Portman CLI option, to pass options for configuring Newman
> newmanOptionsFile CLI option

- README.md
- examples/testsuite-content-tests/crm.openapi.yml
- examples/testsuite-content-tests/crm.postman.json
- examples/testsuite-content-tests/portman-config.crm.json
- examples/testsuite-content-tests/readme.md
- src/application/TestSuite.ts
- src/application/__snapshots__/IntegrationTestWriter.test.ts.snap
- src/application/__snapshots__/TestSuiteIntegrationTests.test.ts.snap
- src/application/__snapshots__/TestSuiteVariations.test.ts.snap
- src/application/__snapshots__/VariationWriter.test.ts.snap
- src/application/tests/__snapshots__/testResponseBodyContent.test.ts.snap
- src/application/tests/__snapshots__/testResponseHeaderContent.test.ts.snap
- src/application/tests/index.ts
- src/application/tests/testResponseBodyContent.test.ts
- src/application/tests/testResponseBodyContent.ts
- src/application/tests/testResponseHeader.ts
- src/application/tests/testResponseHeaderContent.test.ts
- src/application/tests/testResponseHeaderContent.ts
- src/types/PortmanConfig.ts
- src/utils/portman-config-schema.json
Extended the ContentTest capabilities with a "contains" check
> ContentTest - extend requestBody checks / new requestHeader checks

- CHANGELOG.md
- README.md
- examples/testsuite-overwrites/crm.postman.json
- examples/testsuite-overwrites/portman-config.crm.json
- examples/testsuite-overwrites/readme.md
- src/application/overwrites/__snapshots__/overwriteRequestHeaders.test.ts.snap
- src/application/overwrites/__snapshots__/overwriteRequestQueryParams.test.ts.snap
- src/application/overwrites/overwriteRequestHeaders.test.ts
- src/application/overwrites/overwriteRequestHeaders.ts
- src/application/overwrites/overwriteRequestQueryParams.test.ts
- src/application/overwrites/overwriteRequestQueryParams.ts
- src/types/PortmanConfig.ts
- src/utils/portman-config-schema.json
Extended the overwriteRequestHeaders capabilities with the option to insert new headers in Postman.
> overwriteValues - insert header/insert query params

- README.md
- examples/cli-options/crm.postman.json
- examples/cli-options/portman-cli-options.yaml
- examples/cli-options/readme.md
- src/index.ts
Support loading cliOptionsFile in YAML format
> cliOptionsFile in YAML format

- src/services/DownloadService.ts
> Fix typo in OAS URL error string

- .github/workflows/tests.yml
- package-lock.json
- package.json
- src/application/variables/assignVarFromResponseBody.ts
- src/utils/renderChainPath.test.ts
- src/utils/renderChainPath.ts
> Support Node 12

- __tests__/fixtures/crm_compact.postman.json
- __tests__/fixtures/crm_compact.yml
- src/application/TestSuite.test.ts
- src/application/TestSuite.ts
- src/application/__snapshots__/TestSuite.test.ts.snap
A fix for #185, which solves the removal of operations without OperationId when using "excludeForOperations"
> excludeForOperations - Keep operations without operationId

- src/application/Fuzzer.test.ts
- src/application/Fuzzer.ts
- src/application/__snapshots__/Fuzzer.test.ts.snap
Fuzzing - added support for deeply nested required properties in the request body
> Fuzzing - nested required properties

- src/application/globals/writeCollectionPreRequestScripts.test.ts
- src/application/preRequests/writeOperationPreRequestScripts.test.ts
I fixed just one typo, nothing else.
> fix typo: rename collectionPrequestScripts to collectionPreRequestScripts

- examples/testsuite-overwrites/readme.md
- src/application/overwrites/__snapshots__/overwriteRequestHeaders.test.ts.snap
- src/application/overwrites/overwriteRequestHeaders.test.ts
We can disable request headers in overwrite configuration, but there is not any documentation for disable.
> update doc for overwrite RequestHeaders

- CHANGELOG.md
- README.md
- src/application/tests/__snapshots__/testResponseBodyContent.test.ts.snap
- src/application/tests/__snapshots__/testResponseHeaderContent.test.ts.snap
- src/application/tests/testResponseBodyContent.test.ts
- src/application/tests/testResponseBodyContent.ts
- src/application/tests/testResponseHeaderContent.test.ts
- src/application/tests/testResponseHeaderContent.ts
- src/types/PortmanConfig.ts
- src/utils/portman-config-schema.json
- ContentTest - Check minimum length of array or string of response body
- ContentTest - Check maximum length of array or string of response body
- ContentTest - Check minimum length of array or string of response header
- ContentTest - Check maximum length of array or string of response header
> ContentTest - minLength / maxLength

- CHANGELOG.md
- src/application/globals/__snapshots__/orderCollectionRequests.test.ts.snap
- src/application/globals/orderCollectionRequests.test.ts
- src/application/globals/orderCollectionRequests.ts
Fix for order of operations, where the operations have multiple path variables
> order of operations -  multiple path variables + wildcard support

- examples/testsuite-content-tests/crm.postman.json
- examples/testsuite-content-tests/portman-config.crm.json
- examples/testsuite-content-tests/readme.md
- src/application/tests/__snapshots__/testResponseBodyContent.test.ts.snap
- src/application/tests/__snapshots__/testResponseHeaderContent.test.ts.snap
- src/application/tests/testResponseBodyContent.test.ts
- src/application/tests/testResponseHeaderContent.test.ts
- src/application/tests/testResponseHeaderContent.ts
- ContentTest - Check minimum length of array or string of response header
- ContentTest - Check maximum length of array or string of response header
- Updated examples
> content-test-min-max-length

- src/application/TestSuite.ts
A tiny fix, Linked to [#238](https://github.com/apideck-libraries/portman/discussions/238)
> Fix test status code in contract test #238

- src/application/globals/__snapshots__/orderCollectionRequests.test.ts.snap
- src/application/globals/orderCollectionRequests.test.ts
- src/application/globals/orderCollectionRequests.ts
Extended orderOfOperations to include the sorting on root level, next to the folder sorting
> orderOfOperations on root

- CHANGELOG.md
- README.md
- examples/testsuite-content-tests/crm.postman.json
- examples/testsuite-content-tests/portman-config.crm.json
- examples/testsuite-content-tests/readme.md
- src/application/tests/__snapshots__/testResponseBodyContent.test.ts.snap
- src/application/tests/__snapshots__/testResponseHeaderContent.test.ts.snap
- src/application/tests/testResponseBodyContent.test.ts
- src/application/tests/testResponseBodyContent.ts
- src/application/tests/testResponseHeaderContent.test.ts
- src/application/tests/testResponseHeaderContent.ts
- src/types/PortmanConfig.ts
- src/utils/portman-config-schema.json
ContentTest - Added "oneOf" check for "responseBody" & "responseHeader"
> ContentTest - Added "oneOf" check

- CHANGELOG.md
- src/application/tests/__snapshots__/testResponseBodyContent.test.ts.snap
- src/application/tests/testResponseBodyContent.test.ts
- src/application/tests/testResponseBodyContent.ts
Bugfix to handle the setting of length/minLength/maxLength with the value 0 (zero).
> ContentCheck - Handle 0 for length/minLength/maxLength

- CHANGELOG.md
- src/application/overwrites/__snapshots__/overwriteRequestBody.test.ts.snap
- src/application/overwrites/__snapshots__/overwriteRequestHeaders.test.ts.snap
- src/application/overwrites/__snapshots__/overwriteRequestPathVariables.test.ts.snap
- src/application/overwrites/__snapshots__/overwriteRequestQueryParams.test.ts.snap
- src/application/overwrites/overwriteRequestBody.test.ts
- src/application/overwrites/overwriteRequestHeaders.test.ts
- src/application/overwrites/overwriteRequestHeaders.ts
- src/application/overwrites/overwriteRequestPathVariables.test.ts
- src/application/overwrites/overwriteRequestPathVariables.ts
- src/application/overwrites/overwriteRequestQueryParams.test.ts
- src/application/overwrites/overwriteRequestQueryParams.ts
> overwriteRequest - Support empty as value

- CHANGELOG.md
- src/application/overwrites/__snapshots__/overwriteRequestHeaders.test.ts.snap
- src/application/overwrites/__snapshots__/overwriteRequestPathVariables.test.ts.snap
- src/application/overwrites/__snapshots__/overwriteRequestQueryParams.test.ts.snap
- src/application/overwrites/overwriteRequestHeaders.test.ts
- src/application/overwrites/overwriteRequestHeaders.ts
- src/application/overwrites/overwriteRequestPathVariables.test.ts
- src/application/overwrites/overwriteRequestPathVariables.ts
- src/application/overwrites/overwriteRequestQueryParams.test.ts
- src/application/overwrites/overwriteRequestQueryParams.ts
overwrite - Convert boolean values to string for headers, path vars & query params
> overwrites - Convert boolean values to string

- CHANGELOG.md
- README.md
- examples/testsuite-content-tests/crm.postman.json
- examples/testsuite-content-tests/portman-config.crm.json
- examples/testsuite-content-tests/readme.md
- src/__snapshots__/Portman.test.ts.snap
- src/application/__snapshots__/IntegrationTestWriter.test.ts.snap
- src/application/__snapshots__/TestSuite.test.ts.snap
- src/application/__snapshots__/TestSuiteIntegrationTests.test.ts.snap
- src/application/__snapshots__/TestSuiteVariations.test.ts.snap
- src/application/__snapshots__/VariationWriter.test.ts.snap
- src/application/tests/__snapshots__/testResponseBodyContent.test.ts.snap
- src/application/tests/testResponseBodyContent.test.ts
- src/application/tests/testResponseBodyContent.ts
- src/utils/renderChainPath.test.ts
- src/utils/renderChainPath.ts
ContentTests - Added support to lookup a key within an array of objects by using a * wildcard
> ContentTests - lookup a key within in array of objects

- .github/workflows/build.yml
- Dockerfile
> Closes #260 docker image

- CHANGELOG.md
- README.md
- src/application/overwrites/__snapshots__/overwriteRequestBaseUrl.test.ts.snap
- src/application/overwrites/applyOverwrites.ts
- src/application/overwrites/index.ts
- src/application/overwrites/overwriteRequestBaseUrl.test.ts
- src/application/overwrites/overwriteRequestBaseUrl.ts
- src/types/PortmanConfig.ts
- src/utils/portman-config-schema.json
Overwrites - added "overwriteRequestBaseUrl" to overwrite the request base url
> Overwrites - added "overwriteRequestBaseUrl"

- CHANGELOG.md
- src/application/overwrites/__snapshots__/overwriteRequestBaseUrl.test.ts.snap
- src/application/overwrites/overwriteRequestBaseUrl.test.ts
- src/application/overwrites/overwriteRequestBaseUrl.ts
Bugfix for "overwriteRequestBaseUrl" to keep the path parameters
> Bug fix "overwriteRequestBaseUrl"

- CHANGELOG.md
- __tests__/fixtures/portman-config.integration-tests.json
- examples/portman-globals/crm.openapi.yml
- examples/portman-globals/crm.postman.json
- src/__snapshots__/Portman.test.ts.snap
- src/application/IntegrationTestWriter.test.ts
Bugfix for integrationTests - merge folders/suites into one (#361)
> Bugfix for integrationTests - merge folders/suites into one

- src/application/globals/orderCollectionRequests.ts
> orderOfOperations - Prevent error

- CHANGELOG.md
- src/application/overwrites/__snapshots__/overwriteRequestQueryParams.test.ts.snap
- src/application/overwrites/overwriteRequestQueryParams.test.ts
- src/application/overwrites/overwriteRequestQueryParams.ts
> overwriteRequestQueryParams - Enable disabled query params

- src/application/overwrites/overwriteRequestBaseUrl.ts
- src/application/overwrites/overwriteRequestBody.ts
- src/application/overwrites/overwriteRequestHeaders.ts
- src/application/overwrites/overwriteRequestQueryParams.ts
- src/application/overwrites/overwriteRequestSecurity.ts
> overwriteRequestSecurity - Handle missing auth config

- CHANGELOG.md
- examples/cli-filtering/crm.postman.json
- examples/cli-filtering/crm.yml
- src/Portman.ts
- src/application/TestSuite.ts
- src/application/TestSuiteVariations.test.ts
- src/index.ts
> Fix includeTests parameter behaviour

- CHANGELOG.md
- src/application/overwrites/__snapshots__/overwriteRequestHeaders.test.ts.snap
- src/application/overwrites/__snapshots__/overwriteRequestQueryParams.test.ts.snap
- src/application/overwrites/overwriteRequestHeaders.test.ts
- src/application/overwrites/overwriteRequestHeaders.ts
- src/application/overwrites/overwriteRequestQueryParams.test.ts
- src/application/overwrites/overwriteRequestQueryParams.ts
> Auto-enable query parameters when overwrite value is set

- src/postman/PostmanMappedOperation.test.ts
- src/postman/PostmanMappedOperation.ts
> normalizedPathRef: Improve : handling colon character

- CHANGELOG.md
- package-lock.json
- package.json
> Support http & https remote files

- CHANGELOG.md
- package-lock.json
- package.json
- src/services/PostmanDynamicVarGenerator.ts
Linked to #592
Validated & coverage by PostmanDynamicVarGenerator.test.ts
> Replaced faker with @faker-js

- src/application/overwrites/__snapshots__/overwriteRequestQueryParams.test.ts.snap
- src/application/overwrites/overwriteRequestQueryParams.test.ts
- src/application/overwrites/overwriteRequestQueryParams.ts
> overwriteRequestQueryParams - Allow zero value

- CHANGELOG.md
- src/application/overwrites/__snapshots__/overwriteRequestHeaders.test.ts.snap
- src/application/overwrites/__snapshots__/overwriteRequestPathVariables.test.ts.snap
- src/application/overwrites/overwriteRequestHeaders.test.ts
- src/application/overwrites/overwriteRequestHeaders.ts
- src/application/overwrites/overwriteRequestPathVariables.test.ts
- src/application/overwrites/overwriteRequestPathVariables.ts
> overwriteRequest - Allow zero value for path Variables and Headers

- CHANGELOG.md
- package-lock.json
- package.json
- src/application/injectContractTests.test.ts
Dependency chores before a release.
> Bumped dependencies

- CHANGELOG.md
- package-lock.json
- package.json
- src/application/Fuzzer.test.ts
- src/application/Fuzzer.ts
- src/application/__snapshots__/Fuzzer.test.ts.snap
linked to #624 
BEFORE:
AFTER:
> Fuzzing - Fix nested path handling

- README.md
- src/services/OpenApiToPostmanService.ts
Added fallback for parametersResolution
> Conversion - openapi-to-postman fallback parametersResolution

- CHANGELOG.md
- src/application/Fuzzer.test.ts
- src/application/Fuzzer.ts
- src/utils/setByPath.test.ts
- src/utils/setByPath.ts
> Fuzzing - Handle nested plain array values

- package-lock.json
- package.json
> YAML error fix using latest openapi-format

- CHANGELOG.md
- package-lock.json
- package.json
- src/application/overwrites/__snapshots__/overwriteRequestQueryParams.test.ts.snap
- src/application/overwrites/overwriteRequestQueryParams.test.ts
- src/application/overwrites/overwriteRequestQueryParams.ts
- Remove form encoded array query params
- Add additional form encoded array query params
Portman Config:
```
version: 1.0
tests:
integrationTests:
- name: /categories tests
operations:
- openApiOperationId: getAllCategories
openApiResponse: '200'
variations:
- name: ThreeParamsWork
overwrites:
- overwriteRequestQueryParams:
- key: ids
value: 1
- key: ids
value: 2
- key: ids
value: 3
tests:
contentTests:
- responseBodyTests:
- key: categories
minLength: 3
- name: FourthParamIsIgnored
overwrites:
- overwriteRequestQueryParams:
- key: ids
value: 1
- key: ids
value: 2
- key: ids
value: 3
- key: ids
value: 4
tests:
contentTests:
- responseBodyTests:
- key: categories
minLength: 4
- name: TwoParamCauseACrash
overwrites:
- overwriteRequestQueryParams:
- key: ids
value: 1
- key: ids
value: 2 …
```
> overwriteRequestQueryParams - Extend handling form encoded array query params

- CHANGELOG.md
- package-lock.json
- package.json
- src/Portman.ts
- src/oas/OpenApiFormat.ts
> Improved loading split local OpenAPI files

- package-lock.json
- package.json
> fix: scalar $ref: >-

- src/services/PostmanApiService.ts
> Handle Postman API non-200 responses better

- src/utils/matchPath.test.ts
- src/utils/matchPath.ts
> matchPath - Improved matching

- src/application/CollectionWriter.ts
related to #667 
BEFORE
AFTER
---
> Apply casing to auth variable

- src/utils/matchPath.test.ts
- src/utils/matchPath.ts
> matchPath - Improved matching with ending wildcard

- src/index.ts
> fix: Warn about unsupported flags
